language: python
dist: xenial
script: python tests.py
matrix:
  include:
    - name: "Python 2.7"
      python: "2.7"
    - name: "Python 3.6"
      python: "3.6"
    - name: "Python 3.7"
      python: "3.7"
